// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC33a2oQjt8uVfEkzyy8I24OaDNl5q9pOY',
    appId: '1:879628172880:android:7019a925a0065552019b55',
    messagingSenderId: '879628172880',
    projectId: 'uniqart-app',
    storageBucket: 'uniqart-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDR_Uw6xoTFqcaCZUiWJzIzKC8mPirQxo',
    appId: '1:879628172880:ios:5b369adfa91d9ef3019b55',
    messagingSenderId: '879628172880',
    projectId: 'uniqart-app',
    storageBucket: 'uniqart-app.appspot.com',
    androidClientId: '879628172880-3hapunqpd9blh78qshlj6t96em5gf0od.apps.googleusercontent.com',
    iosClientId: '879628172880-ou2ns5r3mgo766j0l97h2o4rv4euk1tk.apps.googleusercontent.com',
    iosBundleId: 'app.uniqart.uniqart',
  );
}
